// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: accommodation_type.sql

package db

import (
	"context"
)

const createAccommodation_type = `-- name: CreateAccommodation_type :one
INSERT INTO accommodation_type (
  type 
) VALUES (
  $1 
)
RETURNING id, type
`

// input: type
// output :one
func (q *Queries) CreateAccommodation_type(ctx context.Context, type_ string) (AccommodationType, error) {
	row := q.db.QueryRowContext(ctx, createAccommodation_type, type_)
	var i AccommodationType
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const deleteAccommodation_type = `-- name: DeleteAccommodation_type :exec
DELETE FROM accommodation_type
WHERE id = $1
`

func (q *Queries) DeleteAccommodation_type(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccommodation_type, id)
	return err
}

const getAccommodation_type = `-- name: GetAccommodation_type :one
SELECT id, type FROM accommodation_type
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccommodation_type(ctx context.Context, id int64) (AccommodationType, error) {
	row := q.db.QueryRowContext(ctx, getAccommodation_type, id)
	var i AccommodationType
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const listAccommodation_types = `-- name: ListAccommodation_types :many
SELECT id, type FROM accommodation_type
ORDER BY type
LIMIT $1
OFFSET $2
`

type ListAccommodation_typesParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListAccommodation_types(ctx context.Context, arg ListAccommodation_typesParams) ([]AccommodationType, error) {
	rows, err := q.db.QueryContext(ctx, listAccommodation_types, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccommodationType{}
	for rows.Next() {
		var i AccommodationType
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccommodation_type = `-- name: UpdateAccommodation_type :one
UPDATE accommodation_type
  set type = $2
WHERE id = $1
RETURNING id, type
`

type UpdateAccommodation_typeParams struct {
	ID   int64  `db:"id"`
	Type string `db:"type"`
}

func (q *Queries) UpdateAccommodation_type(ctx context.Context, arg UpdateAccommodation_typeParams) (AccommodationType, error) {
	row := q.db.QueryRowContext(ctx, updateAccommodation_type, arg.ID, arg.Type)
	var i AccommodationType
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}
