// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type AccommmodationNight struct {
	ID                int64     `db:"id"`
	Accommodation     int64     `db:"accommodation"`
	TripId            int64     `db:"tripId"`
	Date              time.Time `db:"date"`
	ReservationNumber string    `db:"reservationNumber"`
	CreatedAt         time.Time `db:"created_at"`
}

type Accommodation struct {
	ID                       int64  `db:"id"`
	AccommodationName        string `db:"accommodation_name"`
	Pernight                 int64  `db:"pernight"`
	AccommodationType        int64  `db:"accommodation_type"`
	AccommodationDescription string `db:"accommodation_description"`
	Webaddress               string `db:"webaddress"`
	Emailaddress             string `db:"emailaddress"`
	Phonenumber              string `db:"phonenumber"`
	Area                     int64  `db:"area"`
}

type AccommodationType struct {
	ID   int64  `db:"id"`
	Type string `db:"type"`
}

type Activity struct {
	ID            int64        `db:"id"`
	Name          string       `db:"name"`
	ActivityType  int64        `db:"activity_type"`
	Description   string       `db:"description"`
	TimeAllocated sql.NullTime `db:"time_allocated"`
	LocationID    int64        `db:"location_id"`
}

type ActivityDay struct {
	ID         int64     `db:"id"`
	ActivityId int64     `db:"activityId"`
	TripplanId int64     `db:"tripplanId"`
	Date       time.Time `db:"date"`
	CreatedAt  time.Time `db:"created_at"`
}

type ActivityType struct {
	ID   int64  `db:"id"`
	Name string `db:"name"`
}

type CarRental struct {
	ID             int64     `db:"id"`
	Company        string    `db:"Company"`
	Cost           int64     `db:"cost"`
	BookingRef     string    `db:"booking_ref"`
	Website        string    `db:"website"`
	Pickupdate     time.Time `db:"pickupdate"`
	Dropoffdate    time.Time `db:"dropoffdate"`
	Pickuplocation int64     `db:"pickuplocation"`
	Dropoflocation int64     `db:"dropoflocation"`
	TripID         int64     `db:"trip_id"`
	CreatedAt      time.Time `db:"created_at"`
}

type Country struct {
	ID            int64  `db:"id"`
	Name          string `db:"name"`
	ContinentName string `db:"continent_name"`
}

type Flight struct {
	ID               int64     `db:"id"`
	Bookingid        string    `db:"bookingid"`
	AirlineName      string    `db:"airline_name"`
	Airport          string    `db:"airport"`
	Cost             int64     `db:"cost"`
	OriginLocationId int32     `db:"originLocationId"`
	DestinationId    int32     `db:"destinationId"`
	TripID           int64     `db:"trip_id"`
	DepartureDate    time.Time `db:"departure_date"`
	CreatedAt        time.Time `db:"created_at"`
}

type Food struct {
	ID         int64  `db:"id"`
	Name       string `db:"name"`
	Area       int64  `db:"area"`
	FoodType   int64  `db:"food_type"`
	Webaddress string `db:"webaddress"`
}

type FoodPlan struct {
	ID        int64     `db:"id"`
	FoodId    int64     `db:"foodId"`
	TripId    int64     `db:"tripId"`
	Date      time.Time `db:"date"`
	CreatedAt time.Time `db:"created_at"`
}

type FoodType struct {
	ID   int64  `db:"id"`
	Type string `db:"type"`
}

type Location struct {
	ID                  int64  `db:"id"`
	LocationName        string `db:"location_name"`
	LocationDescription string `db:"location_description"`
	CountryID           int64  `db:"country_id"`
}

type Tripplan struct {
	ID        int64     `db:"id"`
	TripName  string    `db:"trip_name"`
	StartDate time.Time `db:"start_date"`
	EndDate   time.Time `db:"end_date"`
	CreatedAt time.Time `db:"created_at"`
}
