// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	// input: name, continent_name
	// output :one
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	DeleteCountry(ctx context.Context, id int64) error
	GetCountry(ctx context.Context, id int64) (Country, error)
	ListCountries(ctx context.Context) ([]Country, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) error
}

var _ Querier = (*Queries)(nil)
